create table EMBARCACION
( 
ID INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(100) NOT NULL,
PUERTO VARCHAR(50) NOT NULL
)
create table DESCARGA 
(
ID INT PRIMARY KEY IDENTITY(1,1),
ID_EMBARCACION INT NOT NULL,
FECHA DATETIME,
TONELADAS DECIMAL,
FOREIGN KEY (ID_EMBARCACION) REFERENCES EMBARCACION(ID)
)


CREATE TABLE LOTE
(
    ID INT PRIMARY KEY IDENTITY(1,1),
    ID_DESCARGA INT NOT NULL,
    NUMERO_LOTE INT,
    TONELADAS_LOTE DECIMAL,
    FOREIGN KEY (ID_DESCARGA) REFERENCES DESCARGA(ID)
);

CREATE TABLE MUESTREO
(
    ID INT PRIMARY KEY IDENTITY(1,1),
    ID_LOTE INT NOT NULL,
    NUMERO_INTENTO INT NOT NULL,
    FECHA DATETIME,
    TBVN DECIMAL(5,2),
    RSW DECIMAL(5,2),
    HUMEDAD DECIMAL(5,2),
    PROTEINA DECIMAL(5,2),
    GRASA DECIMAL(5,2),
    RESULTADO VARCHAR(20),
    FOREIGN KEY (ID_LOTE) REFERENCES LOTE(ID),
    UNIQUE (ID_LOTE, NUMERO_INTENTO)
);
